-- ==============================================================
-- ✅ MODELE PHYSIQUE COMPLET POUR adminInspiraStudio
-- ==============================================================

-- 🔹 Nettoyage : suppression des anciennes tables et contraintes
BEGIN
   EXECUTE IMMEDIATE 'DROP TABLE FINANCER CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE GERER CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE PROJECTS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE RESSOURCES CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SERVICES CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE SPONSORS CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE UTILISER CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE CLIENT CASCADE CONSTRAINTS';
   EXECUTE IMMEDIATE 'DROP TABLE EMPLOYER CASCADE CONSTRAINTS';
EXCEPTION
   WHEN OTHERS THEN NULL;
END;
/

-- ==============================================================
-- TABLE CLIENT
-- ==============================================================
CREATE TABLE CLIENT 
(
   ID_CLIENT      NUMBER(*,0) NOT NULL,
   FIRST_NAME     VARCHAR2(50 BYTE) NOT NULL,
   LAST_NAME      VARCHAR2(50 BYTE) NOT NULL,
   EMAIL          VARCHAR2(50 BYTE) NOT NULL,
   PREFERENCES    VARCHAR2(50 BYTE) NOT NULL,
   CONSTRAINT PK_CLIENT PRIMARY KEY (ID_CLIENT)
);

-- ==============================================================
-- TABLE EMPLOYER
-- ==============================================================
CREATE TABLE EMPLOYER 
(
   ID_EMP        NUMBER(*,0),
   FIRST_NAME    VARCHAR2(50 BYTE) NOT NULL ENABLE,
   LAST_NAME     VARCHAR2(50 BYTE) NOT NULL ENABLE,
   EMAIL         VARCHAR2(50 BYTE) NOT NULL ENABLE,
   PHONE         NUMBER(*,0) NOT NULL ENABLE,
   ROLE          VARCHAR2(80 BYTE) NOT NULL ENABLE,
   PASSWORD      VARCHAR2(20 BYTE) NOT NULL ENABLE,
   STATUS        VARCHAR2(20 BYTE) NOT NULL ENABLE,
   HIRE_DATE     DATE NOT NULL ENABLE,
   AVATAR_PATH   VARCHAR2(100 BYTE) NOT NULL ENABLE,
   CONSTRAINT PK_EMPLOYER PRIMARY KEY (ID_EMP)
   USING INDEX
   TABLESPACE "SYSTEM"
) TABLESPACE "SYSTEM";

-- ==============================================================
-- TABLE SPONSORS
-- ==============================================================
CREATE TABLE SPONSORS 
(
   ID_SPONSOR    NUMBER(*,0) NOT NULL,
   NAME          VARCHAR2(50 BYTE) NOT NULL,
   LAST_UPDATE   DATE NOT NULL,
   EMAIL         VARCHAR2(50 BYTE) NOT NULL,
   STATUS        VARCHAR2(20 BYTE) NOT NULL,
   CONSTRAINT PK_SPONSORS PRIMARY KEY (ID_SPONSOR)
);

-- ==============================================================
-- TABLE PROJECTS
-- ==============================================================
CREATE TABLE PROJECTS 
(
   ID_PROJECT          NUMBER(*,0) NOT NULL,
   ID_CLIENT           NUMBER(*,0) NOT NULL,
   ID_SERVICE          NUMBER(*,0) NOT NULL,
   TITLE               VARCHAR2(50 BYTE) NOT NULL,
   DESCRIPTION         VARCHAR2(50 BYTE) NOT NULL,
   CREATION_DATE       DATE NOT NULL,
   MODIFICATION_DATE   DATE NOT NULL,
   OWNER_ID            NUMBER(*,0) NOT NULL,
   CONSTRAINT PK_PROJECTS PRIMARY KEY (ID_PROJECT)
);

-- ==============================================================
-- TABLE SERVICES
-- ==============================================================
CREATE TABLE SERVICES 
(
   ID_SERVICE     NUMBER(*,0) NOT NULL,
   ID_PROJECT     NUMBER(*,0),
   NAME           VARCHAR2(50 BYTE) NOT NULL,
   DESCRIPTION    VARCHAR2(50 BYTE) NOT NULL,
   CATEGORY       VARCHAR2(50 BYTE) NOT NULL,
   PRICE          FLOAT(50) NOT NULL,
   CREATED_BY     NUMBER(*,0) NOT NULL,
   CONSTRAINT PK_SERVICES PRIMARY KEY (ID_SERVICE)
);

-- ==============================================================
-- TABLE RESSOURCES
-- ==============================================================
CREATE TABLE RESSOURCES 
(
   ID_MEDIA       NUMBER(*,0) NOT NULL,
   TITLE          VARCHAR2(50 BYTE) NOT NULL,
   TYPE           VARCHAR2(50 BYTE) NOT NULL,
   FILE_PATH      VARCHAR2(100 BYTE) NOT NULL,
   FILE_SIZE      FLOAT(50) NOT NULL,
   FORMAT         VARCHAR2(20 BYTE) NOT NULL,
   OWNER_ID       NUMBER(*,0) NOT NULL,
   PROJECT_ID     NUMBER(*,0) NOT NULL,
   UPLOAD_DATE    DATE NOT NULL,
   CONSTRAINT PK_RESSOURCES PRIMARY KEY (ID_MEDIA)
);

-- ==============================================================
-- TABLE FINANCER
-- ==============================================================
CREATE TABLE FINANCER 
(
   ID_SPONSOR     NUMBER(*,0) NOT NULL,
   ID_PROJECT     NUMBER(*,0) NOT NULL,
   CONSTRAINT PK_FINANCER PRIMARY KEY (ID_SPONSOR, ID_PROJECT)
);

CREATE INDEX FINANCER_FK ON FINANCER (ID_SPONSOR ASC);
CREATE INDEX FINANCER2_FK ON FINANCER (ID_PROJECT ASC);

-- ==============================================================
-- TABLE GERER
-- ==============================================================
CREATE TABLE GERER 
(
   ID_PROJECT     NUMBER(*,0) NOT NULL,
   ID_EMP         NUMBER(*,0) NOT NULL,
   CONSTRAINT PK_GERER PRIMARY KEY (ID_PROJECT, ID_EMP)
);

CREATE INDEX GERER_FK ON GERER (ID_PROJECT ASC);
CREATE INDEX GERER2_FK ON GERER (ID_EMP ASC);

-- ==============================================================
-- TABLE UTILISER
-- ==============================================================
CREATE TABLE UTILISER 
(
   ID_EMP         NUMBER(*,0) NOT NULL,
   ID_MEDIA       NUMBER(*,0) NOT NULL,
   CONSTRAINT PK_UTILISER PRIMARY KEY (ID_EMP, ID_MEDIA)
);

CREATE INDEX UTILISER_FK ON UTILISER (ID_EMP ASC);
CREATE INDEX UTILISER2_FK ON UTILISER (ID_MEDIA ASC);

-- ==============================================================
-- CONTRAINTES DE CLES ETRANGERES
-- ==============================================================
ALTER TABLE FINANCER
   ADD CONSTRAINT FK_FINANCER_SPONSOR FOREIGN KEY (ID_SPONSOR)
      REFERENCES SPONSORS (ID_SPONSOR);

ALTER TABLE FINANCER
   ADD CONSTRAINT FK_FINANCER_PROJECT FOREIGN KEY (ID_PROJECT)
      REFERENCES PROJECTS (ID_PROJECT);

ALTER TABLE GERER
   ADD CONSTRAINT FK_GERER_PROJECT FOREIGN KEY (ID_PROJECT)
      REFERENCES PROJECTS (ID_PROJECT);

ALTER TABLE GERER
   ADD CONSTRAINT FK_GERER_EMPLOYER FOREIGN KEY (ID_EMP)
      REFERENCES EMPLOYER (ID_EMP);

ALTER TABLE PROJECTS
   ADD CONSTRAINT FK_PROJECT_CLIENT FOREIGN KEY (ID_CLIENT)
      REFERENCES CLIENT (ID_CLIENT);

ALTER TABLE PROJECTS
   ADD CONSTRAINT FK_PROJECT_SERVICE FOREIGN KEY (ID_SERVICE)
      REFERENCES SERVICES (ID_SERVICE);

ALTER TABLE SERVICES
   ADD CONSTRAINT FK_SERVICE_PROJECT FOREIGN KEY (ID_PROJECT)
      REFERENCES PROJECTS (ID_PROJECT);

ALTER TABLE UTILISER
   ADD CONSTRAINT FK_UTILISER_EMPLOYER FOREIGN KEY (ID_EMP)
      REFERENCES EMPLOYER (ID_EMP);

ALTER TABLE UTILISER
   ADD CONSTRAINT FK_UTILISER_RESSOURCE FOREIGN KEY (ID_MEDIA)
      REFERENCES RESSOURCES (ID_MEDIA);
